version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install

  build:
    commands:
      - zip -r lambda-package.zip ./ -x buildspec.yml
      - echo "Build completed"

  post_build:
    commands:
      - aws lambda update-function-code --function-name Airport --zip-file fileb://lambda-package.zip
      - sleep 10
      - aws lambda update-function-configuration --function-name Airport --handler lambda.handler

artifacts:
  files:
    - lambda-package.zip
