AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Template to provision an S3 bucket, DynamoDB table, and an RDS instance"

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "airline-logs-bucket"

  PassengerCheckInsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "PassengerCheckIns"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "CheckInID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "CheckInID"
          KeyType: "HASH"

  FlightSchedulesDB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: "flight-schedules-db"
      Engine: "postgres"
      DBInstanceClass: "db.t3.micro"
      AllocatedStorage: 20
      MasterUsername: "dbadmin"
      MasterUserPassword: "SecurePassword123"
      PubliclyAccessible: false
      DBName: "flights_db"
      BackupRetentionPeriod: 7

Outputs:
  S3BucketName:
    Description: "Name of the created S3 bucket"
    Value: !Ref S3Bucket

  DynamoDBTableName:
    Description: "Name of the created DynamoDB table"
    Value: !Ref PassengerCheckInsTable

  RDSInstanceEndpoint:
    Description: "Endpoint of the created RDS instance"
    Value: !GetAtt FlightSchedulesDB.Endpoint.Address
